CREATE TABLE pessoa_fisica
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid         UUID,
    mcc          VARCHAR(4)                              NOT NULL,
    cpf          VARCHAR(11)                             NOT NULL,
    nome_pessoa  VARCHAR(50)                             NOT NULL,
    email_pessoa VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_pessoafisica PRIMARY KEY (id)
);
CREATE TABLE pessoa_juridica
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid          UUID,
    mcc           VARCHAR(4)                              NOT NULL,
    cpf           VARCHAR(11)                             NOT NULL,
    cnpj          VARCHAR(14)                             NOT NULL,
    razao_social  VARCHAR(50)                             NOT NULL,
    nome_contato  VARCHAR(50)                             NOT NULL,
    email_contato VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_pessoajuridica PRIMARY KEY (id)
);